version: "3.5"

services:
  commentsy:
    build: .
    image: manjiltamang/commentsy:v1
    restart: always
    env_file:
      - .env.local
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
